[versions]
agp = "8.9.3"
kotlin = "2.1.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.0"
constraintlayout = "2.2.1"
lifecycleViewmodel = "2.10.0"

navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
retrofit = "3.0.0"
okhttpBom = "4.12.0"
moshi = "1.14.0"
coil = "2.4.0"
hilt = "2.57.1"
hilt-navigation = "1.3.0"
room = "2.8.1"


[libraries]
androidx-lifecycle-ktx = {group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodel"}
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
network-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
network-okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttpBom" }
network-okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
network-okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit"}

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

room-runtime = {group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref = "room"}
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref = "room"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}

